from unittest import TestCase
from person import even_or_odd

class TestEvenOrOdd(TestCase):

    def test_check_that_it_only_takes_str_not_str(self):
        self.assertRaises(TypeError, even_or_odd, "12345")

    def test_check_that_it_only_takes_str_not_float(self):
            self.assertRaises(TypeError, even_or_odd, "12345.5")

    def test_check_that_it_only_takes_str_not_list(self):
        self.assertRaises(TypeError, even_or_odd, [12345])
        # self.assertEqual(even_or_odd([123, "tak"]), "Only takes in integer")

    def test_check_that_it_only_takes_str_not_dict(self):
            self.assertRaises(TypeError, even_or_odd, {"num" : 12345.5})

    def test_check_that_it_only_takes_str_not_tuple(self):
        self.assertRaises(TypeError, even_or_odd, (12345, 5))

    def test_check_that_it_only_takes_str_not_bool(self):
            self.assertRaises(TypeError, even_or_odd, False)

    def test_check_that_it_only_takes_str_not_set(self):
        self.assertRaises(TypeError, even_or_odd, {1123455})

    def test_check_that_it_only_takes_str_not_dictt(self):
            self.assertRaises(TypeError, even_or_odd, {"age":123455})

    def test_even_numbers_1_to_100(self):
        self.assertEqual(even_or_odd(2), "Even")
        self.assertEqual(even_or_odd(4), "Even")
        self.assertEqual(even_or_odd(6), "Even")
        self.assertEqual(even_or_odd(8), "Even")
        self.assertEqual(even_or_odd(10), "Even")
        self.assertEqual(even_or_odd(12), "Even")
        self.assertEqual(even_or_odd(14), "Even")
        self.assertEqual(even_or_odd(16), "Even")
        self.assertEqual(even_or_odd(18), "Even")
        self.assertEqual(even_or_odd(20), "Even")
        self.assertEqual(even_or_odd(22), "Even")
        self.assertEqual(even_or_odd(24), "Even")
        self.assertEqual(even_or_odd(26), "Even")
        self.assertEqual(even_or_odd(28), "Even")
        self.assertEqual(even_or_odd(30), "Even")
        self.assertEqual(even_or_odd(32), "Even")
        self.assertEqual(even_or_odd(34), "Even")
        self.assertEqual(even_or_odd(36), "Even")
        self.assertEqual(even_or_odd(38), "Even")
        self.assertEqual(even_or_odd(40), "Even")
        self.assertEqual(even_or_odd(42), "Even")
        self.assertEqual(even_or_odd(44), "Even")
        self.assertEqual(even_or_odd(46), "Even")
        self.assertEqual(even_or_odd(48), "Even")
        self.assertEqual(even_or_odd(50), "Even")
        self.assertEqual(even_or_odd(52), "Even")
        self.assertEqual(even_or_odd(54), "Even")
        self.assertEqual(even_or_odd(56), "Even")
        self.assertEqual(even_or_odd(58), "Even")
        self.assertEqual(even_or_odd(60), "Even")
        self.assertEqual(even_or_odd(62), "Even")
        self.assertEqual(even_or_odd(64), "Even")
        self.assertEqual(even_or_odd(66), "Even")
        self.assertEqual(even_or_odd(68), "Even")
        self.assertEqual(even_or_odd(70), "Even")
        self.assertEqual(even_or_odd(72), "Even")
        self.assertEqual(even_or_odd(74), "Even")
        self.assertEqual(even_or_odd(76), "Even")
        self.assertEqual(even_or_odd(78), "Even")
        self.assertEqual(even_or_odd(80), "Even")
        self.assertEqual(even_or_odd(82), "Even")
        self.assertEqual(even_or_odd(84), "Even")
        self.assertEqual(even_or_odd(86), "Even")
        self.assertEqual(even_or_odd(88), "Even")
        self.assertEqual(even_or_odd(90), "Even")
        self.assertEqual(even_or_odd(92), "Even")
        self.assertEqual(even_or_odd(94), "Even")
        self.assertEqual(even_or_odd(96), "Even")
        self.assertEqual(even_or_odd(98), "Even")
        self.assertEqual(even_or_odd(100), "Even")

    def test_odd_numbers_1_to_99(self):
        self.assertEqual(even_or_odd(1), "Odd")
        self.assertEqual(even_or_odd(3), "Odd")
        self.assertEqual(even_or_odd(5), "Odd")
        self.assertEqual(even_or_odd(7), "Odd")
        self.assertEqual(even_or_odd(9), "Odd")
        self.assertEqual(even_or_odd(11), "Odd")
        self.assertEqual(even_or_odd(13), "Odd")
        self.assertEqual(even_or_odd(15), "Odd")
        self.assertEqual(even_or_odd(17), "Odd")
        self.assertEqual(even_or_odd(19), "Odd")
        self.assertEqual(even_or_odd(21), "Odd")
        self.assertEqual(even_or_odd(23), "Odd")
        self.assertEqual(even_or_odd(25), "Odd")
        self.assertEqual(even_or_odd(27), "Odd")
        self.assertEqual(even_or_odd(29), "Odd")
        self.assertEqual(even_or_odd(31), "Odd")
        self.assertEqual(even_or_odd(33), "Odd")
        self.assertEqual(even_or_odd(35), "Odd")
        self.assertEqual(even_or_odd(37), "Odd")
        self.assertEqual(even_or_odd(39), "Odd")
        self.assertEqual(even_or_odd(41), "Odd")
        self.assertEqual(even_or_odd(43), "Odd")
        self.assertEqual(even_or_odd(45), "Odd")
        self.assertEqual(even_or_odd(47), "Odd")
        self.assertEqual(even_or_odd(49), "Odd")
        self.assertEqual(even_or_odd(51), "Odd")
        self.assertEqual(even_or_odd(53), "Odd")
        self.assertEqual(even_or_odd(55), "Odd")
        self.assertEqual(even_or_odd(57), "Odd")
        self.assertEqual(even_or_odd(59), "Odd")
        self.assertEqual(even_or_odd(61), "Odd")
        self.assertEqual(even_or_odd(63), "Odd")
        self.assertEqual(even_or_odd(65), "Odd")
        self.assertEqual(even_or_odd(67), "Odd")
        self.assertEqual(even_or_odd(69), "Odd")
        self.assertEqual(even_or_odd(71), "Odd")
        self.assertEqual(even_or_odd(73), "Odd")
        self.assertEqual(even_or_odd(75), "Odd")
        self.assertEqual(even_or_odd(77), "Odd")
        self.assertEqual(even_or_odd(79), "Odd")
        self.assertEqual(even_or_odd(81), "Odd")
        self.assertEqual(even_or_odd(83), "Odd")
        self.assertEqual(even_or_odd(85), "Odd")
        self.assertEqual(even_or_odd(87), "Odd")
        self.assertEqual(even_or_odd(89), "Odd")
        self.assertEqual(even_or_odd(91), "Odd")
        self.assertEqual(even_or_odd(93), "Odd")
        self.assertEqual(even_or_odd(95), "Odd")
        self.assertEqual(even_or_odd(97), "Odd")
        self.assertEqual(even_or_odd(99), "Odd")
